[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.30.0"
solana-program = "1.18.14"

[lib]
name = "backend"
crate-type = ["cdylib", "lib"]
